### ISSUE TITLE
Using feross/simple-peer could be great!

### ISSUE THREAD

**Issue by nkittsteiner** [feross/lxjs-chat#1]
Hi there. Maybe it could be good idea to make a twist using your Simple Peer library for a more clean implementation. Thanks Feross for pushing the limits of WebRTC. By the way good news in the Apple world: https://blog.peer5.com/apple-announces-support-for-webrtc-in-safari-11/

**Comment by feross** [comment]
lxjs-chat does use `simple-peer`! I accidentally left the old `peer.js` file in there, so I just deleted it to avoid confusion.
